package uas_pkkp;

import java.sql.Connection;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.view.*;

public class FormMenu extends javax.swing.JFrame {

    public FormMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnData = new javax.swing.JMenu();
        mnPeserta = new javax.swing.JMenuItem();
        mnUser = new javax.swing.JMenuItem();
        mnKabKot = new javax.swing.JMenuItem();
        mnKec = new javax.swing.JMenuItem();
        mnKel = new javax.swing.JMenuItem();
        mnSeleksi = new javax.swing.JMenu();
        mnSeleksiAdm = new javax.swing.JMenuItem();
        mnPenilaian = new javax.swing.JMenuItem();
        mnLaporan = new javax.swing.JMenu();
        mnDataPeserta = new javax.swing.JMenuItem();
        mnLolosAdm = new javax.swing.JMenuItem();
        mnLolosNilai = new javax.swing.JMenuItem();
        mnLolosFinal = new javax.swing.JMenuItem();
        mnUtility = new javax.swing.JMenu();
        cmdBackup = new javax.swing.JMenuItem();
        cmdExit = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Menu");

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selamat Datang");

        jLabel2.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Aplikasi PKKP (Program Pengembangan Kepedulian dan Kepeloporan Pemuda)");

        jLabel3.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Provinsi Jawa Tengah");
        jLabel3.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(203, 203, 203))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(42, 42, 42))
        );

        jMenuBar1.setForeground(new java.awt.Color(255, 255, 0));

        mnData.setText("Data Master");
        mnData.setOpaque(true);

        mnPeserta.setText("Data Peserta");
        mnPeserta.setOpaque(true);
        mnPeserta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPesertaActionPerformed(evt);
            }
        });
        mnData.add(mnPeserta);

        mnUser.setText("Data User");
        mnUser.setOpaque(true);
        mnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUserActionPerformed(evt);
            }
        });
        mnData.add(mnUser);

        mnKabKot.setText("Data Kabupaten/Kota");
        mnKabKot.setOpaque(true);
        mnKabKot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKabKotActionPerformed(evt);
            }
        });
        mnData.add(mnKabKot);

        mnKec.setText("Data Kecamatan");
        mnKec.setOpaque(true);
        mnKec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKecActionPerformed(evt);
            }
        });
        mnData.add(mnKec);

        mnKel.setText("Data Kelurahan");
        mnKel.setOpaque(true);
        mnKel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKelActionPerformed(evt);
            }
        });
        mnData.add(mnKel);

        jMenuBar1.add(mnData);

        mnSeleksi.setText("Seleksi");
        mnSeleksi.setOpaque(true);

        mnSeleksiAdm.setText("Seleksi Administrasi");
        mnSeleksiAdm.setOpaque(true);
        mnSeleksiAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSeleksiAdmActionPerformed(evt);
            }
        });
        mnSeleksi.add(mnSeleksiAdm);

        mnPenilaian.setText("Seleksi Nilai");
        mnPenilaian.setOpaque(true);
        mnPenilaian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPenilaianActionPerformed(evt);
            }
        });
        mnSeleksi.add(mnPenilaian);

        jMenuBar1.add(mnSeleksi);

        mnLaporan.setText("Laporan");
        mnLaporan.setOpaque(true);

        mnDataPeserta.setText("Laporan Data Peserta");
        mnDataPeserta.setOpaque(true);
        mnDataPeserta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDataPesertaActionPerformed(evt);
            }
        });
        mnLaporan.add(mnDataPeserta);

        mnLolosAdm.setText("Laporan Lolos Seleksi Administrasi");
        mnLolosAdm.setOpaque(true);
        mnLolosAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLolosAdmActionPerformed(evt);
            }
        });
        mnLaporan.add(mnLolosAdm);

        mnLolosNilai.setText("Laporan Nilai");
        mnLolosNilai.setOpaque(true);
        mnLolosNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLolosNilaiActionPerformed(evt);
            }
        });
        mnLaporan.add(mnLolosNilai);

        mnLolosFinal.setText("Laporan Peserta Lolos");
        mnLolosFinal.setOpaque(true);
        mnLolosFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLolosFinalActionPerformed(evt);
            }
        });
        mnLaporan.add(mnLolosFinal);

        jMenuBar1.add(mnLaporan);

        mnUtility.setText("Utility");
        mnUtility.setOpaque(true);

        cmdBackup.setText("Backup");
        cmdBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBackupActionPerformed(evt);
            }
        });
        mnUtility.add(cmdBackup);

        cmdExit.setText("Keluar");
        cmdExit.setOpaque(true);
        cmdExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdExitActionPerformed(evt);
            }
        });
        mnUtility.add(cmdExit);

        jMenuBar1.add(mnUtility);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnKabKotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKabKotActionPerformed
        // TODO add your handling code here:
        new FormKabKota().setVisible(true);
    }//GEN-LAST:event_mnKabKotActionPerformed

    private void mnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUserActionPerformed
        // TODO add your handling code here:
        new FormUser().setVisible(true);
    }//GEN-LAST:event_mnUserActionPerformed

    private void cmdExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cmdExitActionPerformed

    private void mnPesertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPesertaActionPerformed
        // TODO add your handling code here:
        new FormPeserta().setVisible(true);
    }//GEN-LAST:event_mnPesertaActionPerformed

    private void mnKecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKecActionPerformed
        // TODO add your handling code here:
        new FormKecamatan().setVisible(true);
    }//GEN-LAST:event_mnKecActionPerformed

    private void mnKelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKelActionPerformed
        // TODO add your handling code here:
        new FormKelurahan().setVisible(true);
    }//GEN-LAST:event_mnKelActionPerformed

    private void mnSeleksiAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSeleksiAdmActionPerformed
        // TODO add your handling code here:
        new FormSeleksiAdm().setVisible(true);
    }//GEN-LAST:event_mnSeleksiAdmActionPerformed

    private void mnPenilaianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPenilaianActionPerformed
        // TODO add your handling code here:
        new FormSeleksiNilai().setVisible(true);
    }//GEN-LAST:event_mnPenilaianActionPerformed

    private void mnDataPesertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDataPesertaActionPerformed
        // TODO add your handling code here:
        new FormSelectPeserta().setVisible(true);
    }//GEN-LAST:event_mnDataPesertaActionPerformed

    private void mnLolosAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLolosAdmActionPerformed
        // TODO add your handling code here:
        new FormSelectLolosAdm().setVisible(true);
    }//GEN-LAST:event_mnLolosAdmActionPerformed

    private void mnLolosNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLolosNilaiActionPerformed
        // TODO add your handling code here:
        new FormLolosSeleksiNilai().setVisible(true);
    }//GEN-LAST:event_mnLolosNilaiActionPerformed

    private void mnLolosFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLolosFinalActionPerformed
        // TODO add your handling code here:
        new FormLolosFinal().setVisible(true);
    }//GEN-LAST:event_mnLolosFinalActionPerformed

    private void cmdBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBackupActionPerformed
        // TODO add your handling code here:
        new FormBackup().setVisible(true);
    }//GEN-LAST:event_cmdBackupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cmdBackup;
    private javax.swing.JMenuItem cmdExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mnData;
    private javax.swing.JMenuItem mnDataPeserta;
    private javax.swing.JMenuItem mnKabKot;
    private javax.swing.JMenuItem mnKec;
    private javax.swing.JMenuItem mnKel;
    private javax.swing.JMenu mnLaporan;
    private javax.swing.JMenuItem mnLolosAdm;
    private javax.swing.JMenuItem mnLolosFinal;
    private javax.swing.JMenuItem mnLolosNilai;
    private javax.swing.JMenuItem mnPenilaian;
    private javax.swing.JMenuItem mnPeserta;
    private javax.swing.JMenu mnSeleksi;
    private javax.swing.JMenuItem mnSeleksiAdm;
    private javax.swing.JMenuItem mnUser;
    private javax.swing.JMenu mnUtility;
    // End of variables declaration//GEN-END:variables
}
